### ISSUE TITLE
How to stop the animation?

### ISSUE THREAD

**Issue by allenwong** [OrRon/ConfettiView#1]
I downloaded the example, it looks amazing, but how to stop the animation?

**Comment by OrRon** [comment]
@allenwong Thanks! Currently, you can't but this will be added in the next release :rocket:

**Comment by allenwong** [comment]
@OrRon Looking forward to see next release:) Well done.

**Comment by OrRon** [comment]
@allenwong https://github.com/OrRon/ConfettiView/blob/master/CHANGELOG.md#016---2016-10-10
