### ISSUE TITLE
Ipad width breaks one aspect. 

### ISSUE THREAD

**Issue by ryleyherrington** [OrRon/ConfettiView#3]
Hey, just tried using it in my app and made a small change to:
https://github.com/OrRon/ConfettiView/blob/master/ConfettiView/Classes/ConfettiLayer.swift#L128

Instead of `380` I used `self.view.frame.size.width` and then it works on iPad as well as iphones and doesn't necessarily use 380 on older devices which are only 320. I'd make a new branch and ask for a PR but honestly this is a very small change and you might not want to do it. But it was just a suggestion!

**Comment by OrRon** [comment]
Thank you @ryleyherrington 🚀 ,

It's small but noticeable and important. 
I will be fixing it in the beginning of the week.

Cheers,
Or.

**Comment by OrRon** [comment]
https://github.com/OrRon/ConfettiView/commit/abc3079b679707dc6196a9093715ad309b3dc184
